#Keeps track of what version your config is in case a new
#modifier is released and needs to be added to your config.
CONFIG_VERSION: 9
AUTOMATICALLY_UPDATE_CONFIG_ON_UPDATE: true
MAXIMUM_BLUEPRINT_CUBOID_SIZE: 512

#Remove or comment out line to remove a modifier from Gadget
#Format: dataValue:ink
#        an ink (data) of 0 is assumed if not included.
#To reset the config to default settings, delete it. The default config
#will be added upon the next load of the plugin.
#If two modifiers are configured to use the same block, the one higher on the list
#will automatically take priority.
PLACE: "42"
TOGGLE: "22"
REMOVE: "57"
NO_PHYSICS: "35:8"
OVERRIDE: "35:14"
INVENTORY: "35:12"
THREE_DIM: "35:13"
TIMER: "35:7"
LINE: "35:2"
AREA: "35:1"
FILTER: "35:4"
SKIP: "35"
PATCH: "159:11"
DUMMY: "35:6"
ADD1: "35:9"
ADD5: "35:11"
ADD10: "35:10"
ADD25: "35:3"
SUBTRACT1: "35:5"
SUBTRACT5: "35:15"
DECODER: "159:5"
RANDOM_NUMBER: "159:4"
RANDOM_BLOCK: "159:0"
GET_INVENTORY: "159:3"
SET_INVENTORY: "159:13"
GET_BLOCK: "159:8"
INVERT_CHECK: "159:14"
CHECK_EQUALS_EXACT: "159:12"
CHECK_EQUALS: "159:7"
CHECK_LESS: "159:2"
CHECK_GREATER: "159:15"
CHECK_PLAYER: "159:10"
CHECK_BLOCK_EQUALS: "159:12"
CHECK_BLOCK_EXISTS: "159:9"